### ISSUE TITLE
about FedCM

### ISSUE THREAD

**Issue by harrylee999** [LINs-lab/FedBR#2]
Thank you so much for sharing the code.
In the FedCM, the momentum function is as follow picture and the author of FedCM suggest hyperparameter **alpha = 0.1**
![image](https://github.com/LINs-lab/FedBR/assets/59381501/54216681-570f-4d45-976e-36012138f2aa)
but in your code, your momentum function is 
![image](https://github.com/LINs-lab/FedBR/assets/59381501/8f4d5c3d-bd87-490a-a7e8-bbcfd2428706)
you change the alpha and (1-alpha)
so i follow the FedCM suggestion,set the **mu = 0.9**,but it doesn't work. however if i set the **mu = 0.1**,it can work but this is different from FedCM paper.
i am very confused about this,is there any details I missed?

**Comment by gyxxyg** [comment]
Thank you for pointing that out, and I apologize for the confusion. In our code, mu = 1 - alpha, so setting mu to 0.1 is equivalent to setting alpha to 0.9 in the FedCM paper. You can simply change "self.mu" to "1 - self.mu" to align the definitions in FedCM.

**Comment by harrylee999** [comment]
yes, setting mu to 0.1 is equivalent to setting alpha to 0.9 in the FedCM paper and it works well with your code.
but in the FedCM paper the author of FedCM suggest hyperparameter alpha = 0.1, alpha should be a small value, so i set mu = 0.9(equivalent to setting alpha to 0.1) with your code，The results were poor and not better than FedAvg. 

have you notice about this? which value of mu you used in your experiment?
i am very confused about this, is there any details I missed?
The images below are from the original FedCM paper, it means alpha should be a small value
![image](https://github.com/LINs-lab/FedBR/assets/59381501/484a8d13-b6d0-4fc2-a51f-f5488238c2e7)

**Comment by gyxxyg** [comment]
Thank you for pointing out that. Upon reviewing the logs and found that:
1. We experimented with varying mu values (0.1, 0.5, 0.9) and found that mu=0.1 yields better performance in our settings.
2. It seems that FedCM is sensitive to alpha's value; occasionally, a very small alpha may lead to models struggling to converge.
3. The disparity may arise from our use of different settings, including larger heterogeneity (Dirichlet-0.1), different number of local steps (50 in our experiments), smaller number of clients, and distinct model architectures.
